apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
      - name: dvwa
        image: vulnerables/web-dvwa
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "p@ssw0rd"
        - name: MYSQL_USER
          value: "dvwa"
        - name: MYSQL_PASSWORD
          value: "dvwa"
        - name: MYSQL_DATABASE
          value: "dvwa"
---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-service
spec:
  type: LoadBalancer
  selector:
    app: dvwa
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
